### ISSUE TITLE
Different behaviour in Chrome and FF - tested with Moodle 3.0

### ISSUE THREAD

**Issue by amandadoughty** [moodleuulm/moodle-atto_styles#7] opened 2016-06-10 11:52 UTC
Hi,
We love this plugin but we are having issues in FF when pressing return after a style section of text. In Chrome a new block is created but in FF the cursor remains in the styled block and you cannot get out of it unless you already had content below. It makes more sense if you look at the screenshot.
![atto](https://cloud.githubusercontent.com/assets/4435897/15963472/3e870744-2f0a-11e6-9776-84d62824eb38.png)

**Comment by abias** [comment] 2016-06-13 05:27
Hi Amanda,

I am happy to see that city university of London is using our little plugin and sorry to hear that it does not work as expected.

I see that there might be something wrong in your screenshot, but I can't reproduce your bug report yet.

Can you please:
- Make sure that you use the latest FF version (recently, I have seen some strange JS bug in FF which was gone with a minor FF update two days later).
- Give me your operating system
- Give the settings of atto_styles in your Moodle installation (especially if you are applying an inline style or a block style)
- Give me the CSS styles which will be applied by atto_style
- Give me a step by step list of actions which have to be done in Atto to reproduce the problem, starting from an empty Atto editor.

Thanks,
Alex

**Comment by amandadoughty** [comment] 2016-06-13 13:54
Hi Alex,

OS: Ubuntu 14.04 (64-bit)
FF: 46.0.1
Chrome: 50.0.2661.102 

To test:
atto_styles set to example:
{
    "title": "Blue box",
    "type": "block",
    "classes": "box blue"
},{
    "title": "Red text",
    "type": "inline",
    "classes": "red"
}

No css styles applied.
1. Navigate to a course
2. Click 'Add activity or resource'
3. Select 'Label'
4. Type 'boo'
5. Highlight 'boo' and apply 'Blue Box'
6. Press return a few times
7. Inspect the code in the editor 

Result in Chrome:

```
<div id="id_introeditoreditable" contenteditable="true" role="textbox" spellcheck="true" aria-live="off" class="editor_atto_content" aria-labelledby="yui_3_17_2_1_1465825383452_444" style="min-height: 208px; height: 208px;">
    <div class="box blue" id="yui_3_17_2_1_1465825383452_1116">
        boo
    </div>
    <div class="box blue" id="yui_3_17_2_1_1465825383452_1116">
        <br>
    </div>
    <div class="box blue" id="yui_3_17_2_1_1465825383452_1116">
        <br>
    </div>
    <div class="box blue" id="yui_3_17_2_1_1465825383452_1116">
        <br>
    </div>
</div>
```

Result in FF:

```
<div contenteditable="true" class="editor_atto_content" aria-live="off" spellcheck="true" role="textbox" id="id_introeditoreditable" aria-labelledby="yui_3_17_2_1_1465824905935_444" style="min-height: 208px; height: 208px;">
    <div class="box blue" id="yui_3_17_2_1_1465824905935_2059">
        boo
        <br>
        <br>
        <br type="_moz">
    </div>
</div>
```

In FF it is not possible to place the cursor outside of the div with the class 'box blue'. The only way to do so is to enter more than one line of text and then highlight and style one line.

I have followed the same test with the inbuilt atto header styles and the result is consistent in both Chrome and FF:

```
<div id="id_introeditoreditable" contenteditable="true" role="textbox" spellcheck="true" aria-live="off" class="editor_atto_content" aria-labelledby="yui_3_17_2_1_1465825383452_444" style="min-height: 208px; height: 208px;">
    <h3 id="yui_3_17_2_1_1465825383452_1418">
        boo
    </h3>
    <p>
        <br>
    </p>
    <p>
        <br>
    </p>
</div>
```

I'm most interested because I tried to write a plugin myself and had this same problem.

**Comment by abias** [comment] 2019-04-10 12:34
Hi @amandadoughty ,

it's been a while since you reported this issue and I am really sorry that it wasn't handled anymore by us.

Today, after publishing the 3.6 release of the plugin, I went through this issue and ran your testing instructions on these browsers:
Google Chrome 73/Mac
Firefox 66/Mac
Safari 12/Mac

The result was the same in all three browsers:
```
<div class="redbox">boo</div>
<div class="redbox"><br></div>
<div class="redbox"><br></div>
<div class="redbox"><br></div>
```

So, I assume that the problem on Firefox has magically disappeared and I dare to close this issue now.

Cheers,
Alex

**Closed as completed by abias** 2019-04-10 12:34 UTC
