### ISSUE TITLE
Styles atto button icon is higher than usual

### ISSUE THREAD

**Issue by danowar2k** [moodleuulm/moodle-atto_styles#16] opened 2019-09-23 12:15 UTC
The styles button icon image is 21px or so high, higher than the other atto icons.

We had to fix this via CSS, but it would be nice if we didn't have to.

**Comment by abias** [comment] 2019-09-23 12:33
Hi Daniel,

I am sorry but I cannot reproduce your issue report. 

Could you please provide a screenshot which shows the issue and the CSS fix which you have applied locally?

Thanks,
Alex

**Comment by Kathrin84** [comment] 2020-02-12 12:43
Hi @danowar2k,

I've also had a look at your reported issue, however I'm also not able to reproduce this:
![atto_bar](https://user-images.githubusercontent.com/4711883/74335801-41f4fc00-4d9d-11ea-902d-d772cd436b91.png)

Al the icons have the same properties:
```
.icon {
    font-size: 16px;
    width: 16px;
    height: 16px;
   (...)
}
```

Because we cannot reproduce this and you did not respond until now, we'll close this issue.

Best, Kathrin

**Closed as completed by Kathrin84** 2020-02-12 12:43 UTC
